/**
 * Stable error codes shared between the backend and frontend.
 *
 * Every user-facing error condition maps to exactly one code. The
 * frontend uses these codes to look up translated messages (i18n);
 * the backend never sends raw user-facing strings.
 *
 * Codes with a `*` suffix accept an optional `detail` field in the
 * {@link ApiError} envelope to carry dynamic context (username, etc.).
 *
 * Grouped by domain for readability — ordering is alphabetical within
 * each group.
 */
export enum ForumErrorCode {
  // ═══ Infrastructure ═══
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_BODY = "INVALID_BODY",
  RATE_LIMITED = "RATE_LIMITED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",

  // ═══ Auth ═══
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_SESSION = "INVALID_SESSION",

  // ═══ Authenticating ═══
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
  USERNAME_TAKEN = "USERNAME_TAKEN",
  USERNAME_INVALID_CHARS = "USERNAME_INVALID_CHARS",
  USERNAME_INVALID_LENGTH = "USERNAME_INVALID_LENGTH",

  // ═══ Sessioning ═══
  SESSION_NOT_ACTIVE = "SESSION_NOT_ACTIVE",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  EXPIRES_AT_IN_PAST = "EXPIRES_AT_IN_PAST",

  // ═══ Profiling ═══
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",

  // ═══ Transport (SDK client only) ═══
  BAD_JSON = "BAD_JSON",
  BAD_STATUS = "BAD_STATUS",
  NETWORK_ERROR = "NETWORK_ERROR",
  HEADER_RESOLUTION_FAILED = "HEADER_RESOLUTION_FAILED",

  // ═══ Assigning ═══
  ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_NOT_DRAFT = "ASSIGNMENT_NOT_DRAFT",
  ASSIGNMENT_NOT_PUBLISHED = "ASSIGNMENT_NOT_PUBLISHED",
  ASSIGNMENT_NOT_REVISABLE = "ASSIGNMENT_NOT_REVISABLE",
  ASSIGNMENT_EVERYONE_NO_TARGETS = "ASSIGNMENT_EVERYONE_NO_TARGETS",
  ASSIGNMENT_TARGETS_REQUIRED = "ASSIGNMENT_TARGETS_REQUIRED",
  RELEASE_ALREADY_EXISTS = "RELEASE_ALREADY_EXISTS",
  RELEASE_NOT_FOUND = "RELEASE_NOT_FOUND",
  RELEASE_NOT_ACTIVE = "RELEASE_NOT_ACTIVE",

  // ═══ Grading ═══
  GRADE_ITEM_NOT_FOUND = "GRADE_ITEM_NOT_FOUND",
  CRITERION_NOT_FOUND = "CRITERION_NOT_FOUND",
  GRADE_NOT_FOUND = "GRADE_NOT_FOUND",
  GRADE_DRAFT_NOT_FOUND = "GRADE_DRAFT_NOT_FOUND",
  GRADE_RELEASED_NOT_FOUND = "GRADE_RELEASED_NOT_FOUND",
  GRADE_ALREADY_RELEASED = "GRADE_ALREADY_RELEASED",
  LEARNER_EXCUSED = "LEARNER_EXCUSED",
  SCORE_OUT_OF_RANGE = "SCORE_OUT_OF_RANGE",

  // ═══ LateBanking ═══
  LATE_DAYS_MUST_BE_POSITIVE = "LATE_DAYS_MUST_BE_POSITIVE",
  LATE_DAYS_NEGATIVE = "LATE_DAYS_NEGATIVE",
  LATE_DAYS_EXCEED_MAX = "LATE_DAYS_EXCEED_MAX",
  LATE_USE_ALREADY_EXISTS = "LATE_USE_ALREADY_EXISTS",
  LATE_USE_NOT_FOUND = "LATE_USE_NOT_FOUND",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",

  // ═══ Linking ═══
  LINK_ALREADY_EXISTS = "LINK_ALREADY_EXISTS",

  // ═══ Locking ═══
  TARGET_ALREADY_LOCKED = "TARGET_ALREADY_LOCKED",
  TARGET_NOT_LOCKED = "TARGET_NOT_LOCKED",

  // ═══ Notifying ═══
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",

  // ═══ Pinning ═══
  ITEM_ALREADY_PINNED = "ITEM_ALREADY_PINNED",
  ITEM_NOT_PINNED = "ITEM_NOT_PINNED",

  // ═══ Posting ═══
  POST_NOT_FOUND = "POST_NOT_FOUND",

  // ═══ Reacting ═══
  REACTION_ALREADY_EXISTS = "REACTION_ALREADY_EXISTS",
  REACTION_NOT_FOUND = "REACTION_NOT_FOUND",

  // ═══ Resolving ═══
  RESOLUTION_NOT_FOUND = "RESOLUTION_NOT_FOUND",

  // ═══ Roling ═══
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  GRANT_ALREADY_EXISTS = "GRANT_ALREADY_EXISTS",
  GRANT_NOT_FOUND = "GRANT_NOT_FOUND",

  // ═══ Rostering ═══
  CLASS_ALREADY_CONFIGURED = "CLASS_ALREADY_CONFIGURED",
  NO_CLASS_CONFIGURED = "NO_CLASS_CONFIGURED",
  SECTION_NOT_FOUND = "SECTION_NOT_FOUND",
  SEAT_NOT_FOUND = "SEAT_NOT_FOUND",
  SEAT_ALREADY_EXISTS = "SEAT_ALREADY_EXISTS",
  SEAT_ALREADY_ACTIVE = "SEAT_ALREADY_ACTIVE",
  SEAT_NOT_PENDING = "SEAT_NOT_PENDING",
  SEAT_NOT_ACTIVE = "SEAT_NOT_ACTIVE",
  SEAT_NOT_DROPPED = "SEAT_NOT_DROPPED",

  // ═══ StudentNoting ═══
  NOTE_NOT_FOUND = "NOTE_NOT_FOUND",
  NOTE_NOT_OPEN = "NOTE_NOT_OPEN",
  NOTE_NOT_RESOLVED = "NOTE_NOT_RESOLVED",
  NOTE_NOT_RESTORABLE = "NOTE_NOT_RESTORABLE",
  NOTE_NOT_LEARNER_VISIBLE = "NOTE_NOT_LEARNER_VISIBLE",
  NOTE_NOT_OWNER = "NOTE_NOT_OWNER",
  INVALID_VISIBILITY = "INVALID_VISIBILITY",

  // ═══ Submitting ═══
  SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND",
  SUBMISSION_REQUIRES_ARTIFACT = "SUBMISSION_REQUIRES_ARTIFACT",
  SUBMISSION_NOT_SUBMITTED = "SUBMISSION_NOT_SUBMITTED",
  SUBMISSION_NOT_WITHDRAWN = "SUBMISSION_NOT_WITHDRAWN",

  // ═══ Subscribing ═══
  ALREADY_SUBSCRIBED = "ALREADY_SUBSCRIBED",
  NOT_SUBSCRIBED = "NOT_SUBSCRIBED",

  // ═══ Tagging ═══
  TAG_NOT_FOUND = "TAG_NOT_FOUND",
  TAG_ALREADY_APPLIED = "TAG_ALREADY_APPLIED",
  TAG_NOT_APPLIED = "TAG_NOT_APPLIED",

  // ═══ Tracking ═══
  ITEM_ALREADY_REGISTERED = "ITEM_ALREADY_REGISTERED",
  ITEM_NOT_REGISTERED = "ITEM_NOT_REGISTERED",
  ITEM_ALREADY_SEEN = "ITEM_ALREADY_SEEN",
  SEEN_MARK_NOT_FOUND = "SEEN_MARK_NOT_FOUND",

  // ═══ Trashing ═══
  ITEM_ALREADY_TRASHED = "ITEM_ALREADY_TRASHED",
  ITEM_NOT_TRASHED = "ITEM_NOT_TRASHED",

  // ═══ Bookmarking ═══
  BOOKMARK_ALREADY_EXISTS = "BOOKMARK_ALREADY_EXISTS",
  BOOKMARK_NOT_FOUND = "BOOKMARK_NOT_FOUND",

  // ═══ Categorizing ═══
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  ITEM_NOT_CATEGORIZED = "ITEM_NOT_CATEGORIZED",

  // ═══ Conversing ═══
  ITEM_ALREADY_IN_CONVERSATION = "ITEM_ALREADY_IN_CONVERSATION",
  PARENT_NODE_NOT_FOUND = "PARENT_NODE_NOT_FOUND",
  NODE_NOT_FOUND = "NODE_NOT_FOUND",
  NODE_HAS_CHILDREN = "NODE_HAS_CHILDREN",

  // ═══ Flagging ═══
  FLAG_ALREADY_EXISTS = "FLAG_ALREADY_EXISTS",
  FLAG_NOT_FOUND = "FLAG_NOT_FOUND",

  // ═══ Formatting ═══
  FORMAT_TARGET_NOT_FOUND = "FORMAT_TARGET_NOT_FOUND",

  // ═══ Linking (additional) ═══
  LINK_NOT_FOUND = "LINK_NOT_FOUND",

  // ═══ Roling (additional) ═══
  ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS",

  // ═══ Tagging (additional) ═══
  TAG_ALREADY_EXISTS = "TAG_ALREADY_EXISTS",
}

/**
 * The canonical error envelope returned to the frontend.
 *
 * `detail` is an optional human-readable context string (username,
 * post id, …) that the frontend may substitute into the translated
 * message template.
 */
export type ApiError = { error: ForumErrorCode; detail?: string };

/** Narrowing guard: is the value an {@link ApiError} envelope? */
export function isApiError(value: unknown): value is ApiError {
  return (
    typeof value === "object" &&
    value !== null &&
    "error" in value &&
    typeof (value as Record<string, unknown>).error === "string"
  );
}
