/**
 * Automates the creation of barrel files for concept imports. It scans the
 * concepts directory and generates:
 *  - `src/concepts/concepts.ts`: production concepts wired to the main database.
 *  - `src/concepts/test_concepts.ts`: concepts wired to a fresh test database.
 *
 * This enables convenient, typed imports like:
 *   `import { User, Post } from "@concepts";`
 *
 * Run this script using `bun run build`.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import * as path from "node:path";

const CONCEPTS_DIR = process.env.CONCEPTS_DIR ?? "src/concepts";

interface ConceptInfo {
  /** PascalCase name, e.g. "User". */
  name: string;
  /** Original directory name, e.g. "User". */
  dirName: string;
  /** Relative import path, e.g. "./User/UserConcept.ts". */
  importPath: string;
}

/**
 * Discovers every valid concept: a directory `{name}` containing a
 * `{name}Concept.ts` file.
 */
function discoverConcepts(baseDir: string): ConceptInfo[] {
  const concepts: ConceptInfo[] = [];
  const absoluteBaseDir = path.resolve(baseDir);

  for (const entry of readdirSync(absoluteBaseDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const conceptDirName = entry.name;
    const fileName = `${conceptDirName}Concept.ts`;
    const conceptFilePath = path.join(absoluteBaseDir, conceptDirName, fileName);

    if (!isFile(conceptFilePath)) continue;

    const conceptName = conceptDirName.charAt(0).toUpperCase() +
      conceptDirName.slice(1);
    concepts.push({
      name: conceptName,
      dirName: conceptDirName,
      importPath: `./${conceptDirName}/${fileName}`,
    });
    console.log(`  -> Found concept: ${conceptName}`);
  }
  return concepts;
}

/** Generates the content of a concepts barrel file (production or test). */
function generateBarrelFileContent(
  concepts: ConceptInfo[],
  isTest: boolean,
): string {
  const dbImportFunc = isTest ? "testDb" : "getDb";

  const header =
    `// This file is auto-generated by the \`generate_imports.ts\` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();
`;

  const dbImport = `import { ${dbImportFunc} } from "@utils/database.ts";\n`;

  const conceptClassImports = concepts
    .map((c) => `import ${c.name}Concept from "${c.importPath}";`)
    .join("\n");

  const conceptTypeExports = concepts
    .map(
      (c) =>
        `export type { default as ${c.name}Concept } from "${c.importPath}";`,
    )
    .join("\n");

  const dbInitialization = `
// Initialize the database connection
export const [db, client] = await ${dbImportFunc}();
`;

  const instantiations = concepts
    .map((c) =>
      `export const ${c.name} = Engine.instrumentConcept(new ${c.name}Concept(db));`
    )
    .join("\n");

  return [
    header,
    dbImport,
    conceptClassImports,
    "",
    conceptTypeExports,
    dbInitialization,
    instantiations,
    "",
  ].join("\n");
}

function isFile(p: string): boolean {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

function main(): void {
  console.log(`Scanning for concepts in '${CONCEPTS_DIR}'...`);
  const concepts = discoverConcepts(CONCEPTS_DIR);
  if (concepts.length === 0) {
    console.warn("Warning: No concepts found. Generated files will be empty.");
  }

  const prodFilePath = path.join(CONCEPTS_DIR, "concepts.ts");
  writeFileSync(prodFilePath, generateBarrelFileContent(concepts, false));
  console.log(`Generated production barrel file: ${prodFilePath}`);

  const testFilePath = path.join(CONCEPTS_DIR, "test_concepts.ts");
  writeFileSync(testFilePath, generateBarrelFileContent(concepts, true));
  console.log(`Generated test barrel file: ${testFilePath}`);

}

if (import.meta.main) {
  main();
}
