/**
 * # Endpoint-spec toolkit (shared by the sync feature files)
 *
 * The forum HTTP API is described by per-feature endpoint specs co-located with
 * the synchronizations that implement them (see each `*.sync.ts` file's
 * `endpoints` manifest and `Endpoints` type). This module holds the type-level
 * helpers those specs reuse. The aggregation of every feature's `Endpoints` into
 * one `AppContract` is generated by `bun run build` (see `contract.generated.ts`),
 * and the SDK consumes that aggregated type.
 *
 * The crucial property preserved here: **output** types are *derived* from the
 * real `@concepts` return types rather than written by hand. Each output is
 * computed from the concept method(s) the matching sync actually invokes, so if a
 * concept's result shape changes, the spec — and therefore the SDK and any
 * frontend built on it — fails to compile. The types stay bound to the backend.
 *
 * Inputs accept ids as plain `string` for ergonomics; outputs preserve the
 * backend's branded {@link ID} type via the derived concept return shapes.
 */
import type { ID } from "@utils/types.ts";

/**
 * The error envelope every endpoint may return instead of its success payload.
 * Mirrors the `{ error }` responses produced throughout the synchronizations and
 * the `Requesting` HTTP server.
 */
export type ApiError = { error: string };

/** Narrows a concept method type `C[K]` to a callable, or `never`. */
type Fn<C, K extends keyof C> = C[K] extends (...args: never[]) => unknown
  ? C[K]
  : never;

/**
 * The success branch of a concept **action** result. Concept actions return
 * `{ ...success } | { error }`; this strips the error branch so the spec reflects
 * the value the success-path sync responds with.
 */
export type ActionOk<C, K extends keyof C> = Exclude<
  Awaited<ReturnType<Fn<C, K>>>,
  ApiError
>;

/**
 * One row of a concept **query** result. Concept queries return arrays of frames;
 * this extracts the element type so a spec can reuse a query's exact row shape
 * (and aggregate it into a list where a sync does so).
 */
export type QueryRow<C, K extends keyof C> = Awaited<ReturnType<Fn<C, K>>> extends
  readonly (infer R)[] ? R : never;

/**
 * Flattens an intersection of object types into a single object literal. Keeps
 * payloads assembled from multiple concept results (e.g. `/auth/login`) readable
 * in editor tooltips and as plain merged shapes for consumers.
 */
export type Prettify<T> = { [K in keyof T]: T[K] } & {};

/**
 * Turns a tuple of input field names into the request body shape. Every endpoint
 * input field is a plain `string` (ids are accepted as strings); an empty tuple
 * yields the no-fields body. This is what binds a spec's declared `input` type to
 * its runtime field-name manifest — they cannot drift within a file.
 */
export type InputShape<F extends readonly string[]> = { [K in F[number]]: string };

/**
 * The runtime shape of a feature's `endpoints` manifest: each path maps to the
 * ordered list of its request input field names. Used as a `satisfies` bound so
 * the manifest stays well-formed without widening its literal types.
 */
export type EndpointInputs = Record<string, { readonly input: readonly string[] }>;

/** Re-exported so specs and the SDK share the branded id type. */
export type { ID };
